site_name: monoDrive Simulator
repo_url: https://github.com/monodriveio/client
docs_dir: docs
theme: readthedocs

pages:
- Home: 'index.md'
- LabVIEW_Client: 'LabVIEW_client.md'
- Detailed_Help:
    - 'Example':
        - 'monoDrive_Simulator_Interface_Example.vi': 'LV_client/monoDrive_Simulator_Interface_Example.md'
    - 'Sensors':
        - 'mono_camera_single.vi': 'LV_client/sensors/monoDrive_lvlib_mono__camera__singlec.md'
        - 'mono_gps.vi': 'LV_client/sensors/monoDrive_lvlib_mono__gpsc.md'
        - 'mono_imu.vi': 'LV_client/sensors/monoDrive_lvlib_mono__imuc.md'
        - 'mono_lidar.vi': 'LV_client/sensors/monoDrive_lvlib_mono__lidar__VLP16__HiResc.md'
        - 'mono_state_sensor.vi': 'LV_client/sensors/monoDrive_lvlib_mono__state__sensorc.md'
        - 'mono_radar.vi': 'LV_client/sensors/monoDrive_lvlib_mono__radarc.md'
        - 'mono_rpm.vi': 'LV_client/sensors/monoDrive_lvlib_mono__rpmc.md'
        - 'mono_send_sensors_config.vi': 'LV_client/sensors/monoDrive_lvlib_mono__send__sensors__configc.md'
        - 'mono_open_sensors_connections.vi': 'LV_client/sensors/monoDrive_lvlib_mono__open_sensors_connections.md'
        - 'mono_veloview_init.vi': 'LV_client/sensors/monoDrive_lvlib_mono__veloview_init.md'
        - 'mono_state_sensor.vi': 'LV_client/sensors/monoDrive_lvlib_mono__state__sensorc.md'
    - 'Simulator':
        - 'mono_check_config_mode.vi': 'LV_client/simulator/monoDrive_lvlib_mono__check__config__modec.md'
        - 'mono_connect.vi': 'LV_client/simulator/monoDrive_lvlib_mono__connectc.md'
        - 'mono_header.vi': 'LV_client/simulator/monoDrive_lvlib_mono__headerc.md'
        - 'mono_init.vi': 'LV_client/simulator/monoDrive_lvlib_mono__initc.md'
        - 'mono_send_command.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__commandc.md'
        - 'mono_send_simulator_config.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__simulator__configc.md'
        - 'mono_send_step.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__stepc.md'
    - 'Utilities':
        - 'Error_Fork_Stacker.vi': 'LV_client/utilities/monoDrive_lvlib_Error_Fork_Stackerc.md'
        - 'mono_build_json.vi': 'LV_client/utilities/monoDrive_lvlib_mono__build__jsonc.md'
        - 'mono_check_simulator.vi': 'LV_client/utilities/monoDrive_lvlib_mono__check__simulatorc.md'
        - 'mono_get_config_path.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__config__pathc.md'
        - 'mono_get_number_trajectories.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__number__trajectoriesc.md'
        - 'mono_matlab_plot_radar.vi': 'LV_client/utilities/monoDrive_lvlib_mono__matlab__plot__radarc.md'
        - 'mono_remove_response_message.vi': 'LV_client/utilities/monoDrive_lvlib_mono__remove__response__message.md'
        - 'mono_sensor_parser.vi': 'LV_client/utilities/monoDrive_lvlib_mono__sensor__parserc.md'
        - 'mono_config_directory_paths.vi': 'LV_client/utilities/mono_config_directory_paths.md'
        - 'mono_reset_to_defaultsc.vi': 'LV_client/utilities/monoDrive_lvlib_mono__reset__to__defaultsc.md'
        - 'mono_read_trajectoryc.vi': 'LV_client/utilities/monoDrive_lvlib_mono__read__trajectoryc.md'
        - 'mono_get_server_response.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__server__responsec.md'
        - 'mono_convert_polar_to_rectangular.vi': 'LV_client/utilities/monoDrive_lvlib_mono__convert__polar__to__rectangularc.md'
        - 'mono_intensity_to_colorc.vi': 'LV_client/utilities/monoDrive_lvlib_mono__intensity__to__colorc.md'
        - 'mono_velodyne_parse.vi': 'LV_client/utilities/monoDrive_lvlib_mono__velodyne__parse.md'
    - 'Weather':
        - 'mono_get_weather.vi': 'LV_client/weather/monoDrive_lvlib_mono__get__weatherc.md'
        - 'mono_weather_update.vi': 'LV_client/weather/monoDrive_lvlib_mono__weather__updatec.md'
    - 'Vehicle':
        - 'mono_send_trajectory.vi': 'LV_client/vehicle/monoDrive_lvlib_mono__send__trajectoryc.md'
        - 'mono_send_vehicle_command.vi': 'LV_client/vehicle/monoDrive_lvlib_mono__send__vehicle__commandc.md'
    
    
markdown_extensions:
  - admonition
