site_name: monoDrive Simulator
repo_url: https://github.com/monodriveio/client
docs_dir: docs
theme: readthedocs

pages:
- Home: 'index.md'
- Configuration:
  - 'System': 'Configuration.md'
  - 'Simulator': 'Simulator-Configuration.md'
  - 'Vehicle': 'Vehicle-Configuration.md'
  - 'Sensors':
    - 'Common': 'Base-Sensor.md'
    - 'Radar': 'Radar.md'
    - 'Lidar': 'Lidar.md'
    - 'Camera': 'Camera.md'
    - 'GPS': 'GPS.md'
    - 'IMU': 'IMU.md'
    - 'RPM': 'RPM.md'
- LabVIEW_Client: 'LabVIEW_client.md'
- Quick-Start: 'Quick-Start Guide v2.0.pdf'
- Detailed_Help:
    - 'Examples': 'LV_client/monoDrive_Simulator_Interface_Example.md'
    - 'Controls':
        - 'monoDrive.ctl': 'LV_client/structures/monoDrive.md'
    - 'Sensors':
        - 'mono_camera_single.vi': 'LV_client/sensors/monoDrive_lvlib_mono__camera__singlec.md'
        - 'mono_depth_camera.vi': 'LV_client/sensors/monoDrive_lvlib_mono__depth__camera.md'
        - 'mono_gps.vi': 'LV_client/sensors/monoDrive_lvlib_mono__gpsc.md'
        - 'mono_imu.vi': 'LV_client/sensors/monoDrive_lvlib_mono__imuc.md'
        - 'mono_lidar.vi': 'LV_client/sensors/monoDrive_lvlib_mono__lidarc.md'
        - 'mono_state_sensor.vi': 'LV_client/sensors/monoDrive_lvlib_mono__state__sensorc.md'
        - 'mono_radar.vi': 'LV_client/sensors/monoDrive_lvlib_mono__radarc.md'
        - 'mono_rpm.vi': 'LV_client/sensors/monoDrive_lvlib_mono__rpmc.md'
        - 'mono_state_sensor.vi': 'LV_client/sensors/monoDrive_lvlib_mono__state__sensorc.md'
        - 'mono_ultrasonic.vi': 'LV_client/sensors/mono_ultrasonic.md'
    - 'Simulator':
        - 'mono_check_config_mode.vi': 'LV_client/simulator/monoDrive_lvlib_mono__check__config__modec.md'
        - 'mono_connect.vi': 'LV_client/simulator/monoDrive_lvlib_mono__connectc.md'
        - 'mono_header.vi': 'LV_client/simulator/monoDrive_lvlib_mono__headerc.md'
        - 'mono_send_command.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__commandc.md'
        - 'mono_send_step.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__stepc.md'
        - 'mono_send_simulator_config.vi': 'LV_client/simulator/monoDrive_lvlib_mono__send__simulator__configc.md'

    - 'Utilities':
        - 'Error_Fork_Stacker.vi': 'LV_client/utilities/monoDrive_lvlib_Error_Fork_Stackerc.md'
        - 'mono_build_json.vi': 'LV_client/utilities/monoDrive_lvlib_mono__build__jsonc.md'
        - 'mono_check_simulator.vi': 'LV_client/utilities/monoDrive_lvlib_mono__check__simulatorc.md'
        - 'mono_get_config_path.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__config__pathc.md'
        - 'mono_config_directory_paths.vi': 'LV_client/utilities/mono_config_directory_paths.md'
        - 'mono_get_number_trajectories.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__number__trajectoriesc.md'
        - 'mono_matlab_plot_radar.vi': 'LV_client/utilities/monoDrive_lvlib_mono__matlab__plot__radarc.md'
        - 'mono_remove_response_message.vi': 'LV_client/utilities/monoDrive_lvlib_mono__remove__response__message.md'
        - 'mono_sensor_parser.vi': 'LV_client/utilities/monoDrive_lvlib_mono__sensor__parserc.md'
        - 'mono_read_trajectoryc.vi': 'LV_client/utilities/monoDrive_lvlib_mono__read__trajectoryc.md'
        - 'mono_convert_polar_to_rectangular.vi': 'LV_client/utilities/monoDrive_lvlib_mono__convert__polar__to__rectangularc.md'
        - 'mono_intensity_to_colorc.vi': 'LV_client/utilities/monoDrive_lvlib_mono__intensity__to__colorc.md'
        - 'mono_velodyne_parse.vi': 'LV_client/utilities/monoDrive_lvlib_mono__velodyne__parse.md'
        - 'mono__check_simulator_version.vi': 'LV_client/utilities/monoDrive_lvlib_mono__check__simulator__versionc.md'
        - 'mono_lidar_packages.vi': 'LV_client/utilities/monoDrive_lvlib_mono__lidar__packages.md'
        - 'mono_lidar_plot.vi': 'LV_client/utilities/monoDrive_lvlib_mono__lidar__plotc.md'
        - 'mono_simulink_image.vi': 'LV_client/utilities/monoDrive_lvlib_mono__simulink__imagec.md'
        - 'mono_get_no_points_lidar.vi': 'LV_client/utilities/monoDrive_lvlib_mono__get__no__points__lidarc.md'
        - 'mono_parse_lidar_configuration.vi': 'LV_client/utilities/monoDrive_lvlib_mono__parse__lidar__configurationc.md'
        - 'parse_lidar_raw_data.vi': 'LV_client/utilities/parse_lidar_raw_data.md'
        - 'mono_get_stream_dimensions.vi' : 'LV_client/utilities/mono_get_stream_dimensions.md'
        - 'calculate_orientation_xyz.vi' : 'LV_client/utilities/calculate_orientation_xyz.md'
        - 'mono_select_map.vi' : 'LV_client/utilities/mono_select_map.md'
        - 'mono_radar_plot.vi' : 'LV_client/utilities/mono_radar_plot.md'
        - 'mono_GrayScaleToSimulink.vi': 'LV_client/utilities/mono_GrayScaleToSimulink.md'
        - 'radar_flag.vi': 'LV_client/utilities/radar_flag.md'
    - 'Weather':
        - 'mono_get_weather.vi': 'LV_client/weather/monoDrive_lvlib_mono__get__weatherc.md'
        - 'mono_weather_update.vi': 'LV_client/weather/monoDrive_lvlib_mono__weather__updatec.md'
        - 'mono_weather_id.vi': 'LV_client/weather/monoDrive_lvlib_mono__weather__idc.md'
    - 'Vehicle':
        - 'mono_send_trajectory.vi': 'LV_client/vehicle/monoDrive_lvlib_mono__send__trajectoryc.md'
        - 'mono_send_vehicle_command.vi': 'LV_client/vehicle/monoDrive_lvlib_mono__send__vehicle__commandc.md'
        

markdown_extensions:
  - admonition
