site_name: monoDrive Simulator
repo_url: https://github.com/monodriveio/client
docs_dir: docs
theme: readthedocs

pages:
- Home: 'index.md'
- Installation: 'Installation.md'
- Configuration:
  - 'System': 'Configuration.md'
  - 'Simulator': 'Simulator-Configuration.md'
  - 'Vehicle': 'Vehicle-Configuration.md'
  - 'Sensors':
    - 'Common': 'Base-Sensor.md'
    - 'Radar': 'Radar.md'
    - 'Lidar': 'Lidar.md'
    - 'Multi Camera': 'Multi-Camera.md'
    - 'Camera': 'Camera.md'
    - 'GPS': 'GPS.md'
    - 'IMU': 'IMU.md'
    - 'Waypoint': 'Waypoint.md'
    - 'Bounding Box': 'Bounding-Box.md'
    - 'RPM': 'RPM.md'
- LabVIEW_Client: 'LabVIEW_client.md'
- Detailed_Help:
    - 'Example':
        - 'monoDrive_Simulator_Interface_Example.vi': 'LV_client\monoDrive_Simulator_Interface_Example.md'
    - 'Sensors':
        - 'mono_camera_single.vi': 'LV_client\sensors\monoDrive_lvlib_mono__camera__singlec.md'
        - 'mono_gps.vi': 'LV_client\sensors\monoDrive_lvlib_mono__gpsc.md'
        - 'mono_imu.vi': 'LV_client\sensors\monoDrive_lvlib_mono__imuc.md'
        - 'mono_lidar.vi': 'LV_client\sensors\monoDrive_lvlib_mono__lidarc.md'
        - 'mono_proccess_camera.vi': 'LV_client\sensors\monoDrive_lvlib_mono__proccess__camerac.md'
        - 'mono_radar.vi': 'LV_client\sensors\monoDrive_lvlib_mono__radarc.md'
        - 'mono_send_sensors_config.vi': 'LV_client\sensors\monoDrive_lvlib_mono__send__sensors__configc.md'
        - 'mono_sensors_open_port.vi': 'LV_client\sensors\monoDrive_lvlib_mono__sensors__open__portsc.md'
    - 'Simulator':
        - 'mono_check_config_mode.vi': 'LV_client\simulator\monoDrive_lvlib_mono__check__config__modec.md'
        - 'mono_connect.vi': 'LV_client\simulator\monoDrive_lvlib_mono__connectc.md'
        - 'mono_heade.vi': 'LV_client\simulator\monoDrive_lvlib_mono__headerc.md'
        - 'mono_init.vi': 'LV_client\simulator\monoDrive_lvlib_mono__initc.md'
        - 'mono_send_command.vi': 'LV_client\simulator\monoDrive_lvlib_mono__send__commandc.md'
        - 'mono_send_simulator_config.vi': 'LV_client\simulator\monoDrive_lvlib_mono__send__simulator__configc.md'
        - 'mono_send_step.vi': 'LV_client\simulator\monoDrive_lvlib_mono__send__stepc.md'
    - 'Utilities':
        - 'deserializerc.vi': 'LV_client\utilities\monoDrive_lvlib_deserializerc.md'
        - 'Error_Fork_Stacker.vi': 'LV_client\utilities\monoDrive_lvlib_Error_Fork_Stackerc.md'
        - 'mono_build_json.vi': 'LV_client\utilities\monoDrive_lvlib_mono__build__jsonc.md'
        - 'mono_check_simulator.vi': 'LV_client\utilities\monoDrive_lvlib_mono__check__simulatorc.md'
        - 'mono_get_config_path.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__config__pathc.md'
        - 'mono_get_frames.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__framesc.md'
        - 'mono_get_number_trajectories.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__number__trajectoriesc.md'
        - 'mono_get_sensor_connections.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__sensor__connectionsc.md'
        - 'mono_get_simulator_mode.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__simulator__modec.md'
        - 'mono_get_vehicles.vi': 'LV_client\utilities\monoDrive_lvlib_mono__get__vehiclesc.md'
        - 'mono_initialization.vi': 'LV_client\utilities\monoDrive_lvlib_mono__initializationc.md'
        - 'mono_matlab_plot_radar.vi': 'LV_client\utilities\monoDrive_lvlib_mono__matlab__plot__radarc.md'
        - 'mono_remove_response_message.vi': 'LV_client\utilities\monoDrive_lvlib_mono__remove__response__message.md'
        - 'mono_sensor_parser.vi': 'LV_client\utilities\monoDrive_lvlib_mono__sensor__parserc.md'
        - 'mono_set_defaults.vi': 'LV_client\utilities\monoDrive_lvlib_mono__set__defaultsc.md'
    - 'Vehicle':
        - 'mono_send_trajectory.vi': 'LV_client\vehicle\monoDrive_lvlib_mono__send__trajectoryc.md'
        - 'mono_send_vehicle_command.vi': 'LV_client\vehicle\monoDrive_lvlib_mono__send__vehicle__commandc.md'
    
- Starting the Simulator: 'Starting-Simulator.md'

markdown_extensions:
  - admonition
